### POST request to create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "JohnchikADdssdfsd123Kafka DoeHiNewsdfds",
  "email": "kafkatest1234561assfsdqweqwedasd23132WithKafkaConsumersdfkc@mail.com",
  "address": "123a NewMainNewMainNewNew Street",
  "dateOfBirth": "1995-11-11",
  "registeredDate": "2025-11-19"
}
