### PUT updates an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "NewName",
  "email": "newtest@example.com",
  "address": "NewAddress",
  "dateOfBirth": "1992-09-11"
}
